### PR TITLE
Added mpv support, hit alt+w to seamlessly convert and then switch over

### PR DESCRIPTION
**Pull request by MatthewBregg**
Just load auto_convert into mpv, then set the path for the sofa file, and for the DSVSCA executable

also, in the .lua file, change the hardcoded sofa file to be wherever your sofa file is, and same for the DSVSCA executable.

### CODE REVIEW

**Comment by MatthewBregg** [comment]
For the makefiles, I had to add llzma and -lbz2 to get it to compile for me.
Also still have commented ui lines in makefile.

**Comment by MatthewBregg** [comment]
Figured out why it paused.

I have a plugin that automatically remembers the state of all video files I played, so when I exit and resume, it resumes with same position, volume, and... pause/unpause state.
So when I showed you, I started the file, converted, then once converted, paused and closed....

So when the file was reloaded, it it unpaused, but then the plugin to restore video state ran and overrode my unpause.

**Comment by clandry94** [comment]
This looks good, I'm going to make some changes over the week to integrate it with the CLI as well as take care of the llzma, lva, and lbz2 deps.

**Comment by MatthewBregg** [comment]
Sounds good, I'll be keeping an eye on it.

**Comment by MatthewBregg** [comment]
Lua also has a really good functionality to call into C code.
I've worked with lua calling to C before, and it's really easy to do, so maybe could interface in a nicer manner than os.execute.

**Comment by MatthewBregg** [comment]
Merged in the pr you created.

**Pull request merged**
